[package]
name = "tes3mp-plugin"
description = "Stubs for creating a TES3MP server plugin"
homepage = "https://git.cijber.net/teamnwah/tes3mp-rs"
version = "0.1.0"
authors = ["eater <=@eater.me>"]
edition = "2018"